POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoiZmVsYUBnbWFpbC5jb20iLCJpYXQiOjE3NTA3NjMyNTAsImV4cCI6MTc1MDc2Njg1MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.4nPhBQybAZNz1NL16EO6wsEYV9xamyYZNAj8M8TTIUk


{
    "title": "Donald trump has called for a complete cease-fire",
    "postType": "post",
    "slug": "usa-iran-war",
    "status": "draft",
    "content": "The war condition is currently brewing up amongst both party",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\" \r\n}",
    "featuredImageUrl": "https://i.pinimg.com/736x/e4/4a/a1/e44aa117af8e511fc7353735e963f6b8.jpg",
    "publishOn": "2025-06-14T10:32:45.000Z",
    "tags": [2],
    "metaOptions": {
        "metaValue": "{\"sideBarEnabled\": true, \"footerActive\": true }"
    }
}