POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTc1MDY5MTQ4OSwiZXhwIjoxNzUwNzc3ODg5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.QskKhbnJKZq81iiyJwEEfd7f8DwSy6jupDlfnhLbjmY"
}